parameters:
  redis.database.name: 'redis'
  redis.cache.name: 'l2'

services:
  cache.redis:
    class: RedisInterface
    factory: ['@cache.storage', getCache]
    arguments:
      - '%redis.cache.name%'
  database.redis:
    parent: database.abstract
    class: Vain\Redis\Database\RedisDatabase
    arguments: ['@connection.redis.database']
  cache.factory.credis:
    class: Vain\Redis\Cache\Factory\CRedisCacheFactory
    arguments: ['credis']
    tags:
      - {name: cache.factory}
  connection.redis.database:
    factory: ['@connection.factory.credis', 'createConnection']
    arguments:
      - '%redis.database.name%'
  connection.redis.cache:
    factory: ['@connection.factory.credis', 'createConnection']
    arguments:
      - '%redis.cache.name%'
  connection.factory.credis:
    parent: connection.factory.abstract
    class: Vain\Redis\Connection\Factory\CRedisConnectionFactory
  connection.factory.credis.proxy:
    class: Vain\Core\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.factory.credis
    decoration_priority: 100
    arguments: ['@connection.factory.credis.proxy.inner']