parameters:
  redis.database: 'redis'
  credis.config.required.fields: ['host', 'port', 'db']

services:
  database.redis:
    class: Vain\Redis\RedisInterface
    factory: ['@database.storage', getDatabase]
    arguments:
      - '%redis.database%'
  database.factory.credis:
    class: Vain\Redis\Database\Factory\CRedisDatabaseFactory
    arguments: ['credis']
    tags:
      - {name: database.factory}
  cache.factory.credis:
    class: Vain\Redis\Cache\Factory\CRedisCacheFactory
    arguments: ['credis']
    tags:
      - {name: cache.factory}
  connection.factory.credis.trust:
    class: Vain\Redis\Connection\Factory\CRedisConnectionFactory
    arguments: ['credis']
  connection.factory.credis.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    arguments: ['@connection.factory.credis.trust', '%credis.config.required.fields%']
  connection.factory.credis:
    alias: connection.factory.credis.assert
    tags:
      - {name: connection.factory}
