parameters:
  redis.connection.database: 'redis'
  redis.connection.cache: 'l2'

services:
  cache.redis:
    parent: database.abstract
    class: Vain\Redis\Database\RedisDatabase
    arguments: ['@connection.redis.cache']
  database.redis:
    parent: database.abstract
    class: Vain\Redis\Database\RedisDatabase
    arguments: ['@connection.redis.database']
  cache.factory.credis:
    class: Vain\Redis\Cache\Factory\CRedisCacheFactory
    arguments: ['credis']
    tags:
      - {name: cache.factory}
  connection.redis.database:
    parent: connection.abstract
    class: Vain\Redis\Connection\CRedisConnection
    arguments: ['%redis.connection.database%']
    tags:
      - {name: connection}
  connection.redis.cache:
    parent: connection.abstract
    class: Vain\Redis\Connection\CRedisConnection
    arguments: ['%redis.connection.cache%']
    tags:
      - {name: connection}