parameters:
  redis.database.name: 'redis'
  redis.cache.name: 'l2'

services:
  cache.redis:
    class: RedisInterface
    factory: ['@cache.storage', getCache]
    arguments:
      - '%redis.cache.name%'
  database.redis:
    class: Vain\Redis\RedisInterface
    factory: ['@database.storage', getDatabase]
    arguments:
      - '%redis.database.name%'
  database.factory.credis:
    class: Vain\Redis\Database\Factory\CRedisDatabaseFactory
    arguments: ['credis']
    tags:
      - {name: database.factory}
  cache.factory.credis:
    class: Vain\Redis\Cache\Factory\CRedisCacheFactory
    arguments: ['credis']
    tags:
      - {name: cache.factory}
  connection.factory.credis:
    class: Vain\Redis\Connection\Factory\CRedisConnectionFactory
    arguments: ['credis']
    tags:
      - {name: connection.factory}
  connection.factory.credis.proxy:
    class: Vain\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.factory.credis
    decoration_priority: 100
    arguments: ['@connection.factory.credis.proxy.inner']
