imports:
  - { resource: '../di.yml' }

parameters:
  credis.config.required.fields: ['host', 'port', 'db']

services:
  connection.factory.credis.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    decorates: connection.factory.credis
    arguments: ['@connection.factory.credis.assert.inner', '%credis.config.required.fields%']
